version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 44320:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    ports:
      - 44420:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  mysqlc:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=gnucannabis
      - MYSQL_DATABASE=gnucannabis
      - MYSQL_USER=gnucannabis
      - MYSQL_PASSWORD=gnucannabis
    ports:
      - "3307:3306"

  #pgsql:
  #  image: postgres:9.5SS
  #  environment:
  #    - POSTGRES_DB=yii2advanced
  #    - POSTGRES_USER=yii2advanced
  #    - POSTGRES_PASSWORD=secret